### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 807502278** [ZHO-ZHO-ZHO/ComfyUI-SD3-Medium-CN-Diffusers#1]
Traceback (most recent call last):
  File "D:\AI\ComfyUI-3D\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-SD3-Medium-CN-Diffusers\__init__.py", line 1, in <module>
    from . import SD3CN
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-SD3-Medium-CN-Diffusers\SD3CN.py", line 5, in <module>
    from diffusers.models.controlnet_sd3 import ControlNetSD3Model
ImportError: cannot import name 'ControlNetSD3Model' from 'diffusers.models.controlnet_sd3' (D:\AI\ComfyUI-3D\ComfyUI\python_miniconda\Lib\site-packages\diffusers\models\controlnet_sd3.py)

Cannot import D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-SD3-Medium-CN-Diffusers module for custom nodes: cannot import name 'ControlNetSD3Model' from 'diffusers.models.controlnet_sd3' (D:\AI\ComfyUI-3D\ComfyUI\python_miniconda\Lib\site-packages\diffusers\models\controlnet_sd3.py)

**Comment by 807502278** [comment]
我先安装了requirements.txt
然后安装了这个
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-SD3-Medium-CN-Diffusers/assets/46019416/c0c2584e-f3f0-4e88-a114-04c9c887b526)
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-SD3-Medium-CN-Diffusers/assets/46019416/735083cc-dffb-4691-ab56-80352e413410)
